name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ec2-15-222-234-51.ca-central-1.compute.amazonaws.com
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port:   22
        script: whoami
        debug: true # Enable debug output

    - name: Fetch GitHub Actions IP ranges
      id: github-ips
      run: |
        echo "::set-output name=ips::$(curl -s https://api.github.com/meta)"
    - name: Whitelist GitHub Actions IPs on your server
      run: |
        # Replace the following command with the appropriate command for your server to whitelist IPs
        echo "${{ steps.github-ips.outputs.ips }}" | while read ip; do sudo ufw allow from $ip to any port  22; done



    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
          switches: -avzr --delete
          path: ./
          remote_path: /var/www/html
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}
          args: --no-perms -O 
