name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host:  127.0.0.1
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port:   22
        script: whoami
        debug: true # Enable debug output


    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
          switches: -avzr --delete
          path: ./
          remote_path: /var/www/html
          remote_host: 127.0.0.1
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}
          args: --no-perms -O 
